const $=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';
let worker,ready=false,busy=false,result=null,position=0,timer=null,revision=0;
function element(tag,attrs={},text){const e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e;}
function controls(){const done=!result||position>=result.trace.length-1;for(const id of ['play','step','finish'])$(id).disabled=!ready||busy||done;$('run').disabled=!ready||busy;$('progress').disabled=!result||busy;}
function pause(){clearTimeout(timer);timer=null;$('play').textContent='Play';}
function route(){if(!result)return;const s=result.trace[position],order=$('view').value==='best'?s.best_route:s.route;const point=i=>[result.points[i][0]*4+50,result.points[i][1]*4+15];$('route').replaceChildren();$('route').append(element('polyline',{points:[...order,order[0]].map(i=>point(i).join(',')).join(' ')}));result.points.forEach((p,i)=>{const [x,y]=point(i);$('route').append(element('circle',{cx:x,cy:y,r:4}),element('text',{x:x+7,y:y-7},i+1));});$('route').setAttribute('aria-label',`${$('view').value==='best'?'Best':'Current'} route at move ${position}, distance ${($('view').value==='best'?s.best:s.cost).toFixed(1)}.`);}
function chart(){const trace=result.trace.slice(0,position+1),height=140,width=810,x0=65,y0=15;const min=Math.min(...result.trace.map(s=>Math.min(s.best,s.hill)))*.95,max=Math.max(...result.trace.map(s=>s.cost))*1.03;const xy=(s,k)=>[x0+s.step/result.iterations*width,y0+height-(s[k]-min)/(max-min)*height];$('chart').replaceChildren();for(let i=0;i<3;i++){const y=y0+i*height/2;$('chart').append(element('line',{x1:x0,y1:y,x2:x0+width,y2:y,stroke:'#c8d2e0','stroke-width':.7}),element('text',{x:8,y:y+4},(max-i*(max-min)/2).toFixed(0)));}for(const [k,color]of [['cost','#8c9db4'],['hill','#956ac7'],['best','#397ee8']])$('chart').append(element('polyline',{points:trace.map(s=>xy(s,k).join(',')).join(' '),fill:'none',stroke:color,'stroke-width':k==='cost'?1:2}));$('chart').append(element('text',{x:x0,y:177},'0'),element('text',{x:x0+width-30,y:177},result.iterations));$('chart').setAttribute('aria-label',`Distance history through move ${position}. Annealing best ${trace.at(-1).best.toFixed(1)}, hill climbing ${trace.at(-1).hill.toFixed(1)}.`);}
function render(){if(!result)return;const s=result.trace[position];$('current').textContent=s.cost.toFixed(1);$('best').textContent=s.best.toFixed(1);$('heat').textContent=s.temperature.toFixed(3);$('delta').textContent=position?(s.delta>0?'+':'')+s.delta.toFixed(2):'—';$('probability').textContent=position?(s.probability*100).toFixed(1)+'%':'—';$('uphill').textContent=s.uphill;$('progress').value=position;$('position').textContent=`${position} / ${result.iterations}`;$('status').className=position&&s.accepted&&s.delta>0?'uphill':s.accepted?'better':'';$('status').textContent=position===0?'Starting tour. Press Play or Step.':s.accepted?(s.delta>0?'Accepted a longer route.':s.delta<0?'Accepted a shorter route.':'Accepted an equal-cost move.'):'Rejected this move.';const improvement=(1-s.best/result.initial)*100;const gap=s.hill-s.best;$('comparison').textContent=`Best: ${s.best.toFixed(1)} · Hill climbing: ${s.hill.toFixed(1)} · ${improvement.toFixed(1)}% shorter than the start.`+(position===result.iterations?(Math.abs(gap)<1e-8?' Both finished at the same distance.':gap>0?' Annealing found the shorter tour this run.':' Hill climbing found the shorter tour this run.'):'');route();chart();controls();}
function advance(){if(result&&position<result.trace.length-1){position++;render();}}
function play(){advance();if(position<result.trace.length-1){$('play').textContent='Pause';timer=setTimeout(play,25);}else pause();}
function fail(){pause();ready=false;busy=false;controls();$('retry').hidden=false;$('status').textContent='Python couldn’t load or run. Try again.';}
function init(){if(worker)worker.terminate();ready=false;busy=false;pause();controls();$('retry').hidden=true;$('status').textContent='Loading Python…';worker=new Worker('worker.js',{type:'module'});worker.onerror=fail;worker.onmessage=({data})=>{if(data.id!==undefined&&data.id!==revision)return;if(data.type==='ready'){ready=true;controls();run();}else if(data.type==='error')fail();else{busy=false;result=data.result;position=0;$('progress').max=result.iterations;render();}};}
function run(){if(!ready||!$('settings').reportValidity())return;pause();busy=true;revision++;controls();$('status').textContent='Calculating moves…';worker.postMessage({id:revision,settings:{seed:Number($('seed').value),temperature:Number($('temperature').value),cooling:Number($('cooling').value),iterations:Number($('iterations').value)}});}
$('settings').onsubmit=e=>{e.preventDefault();run();};$('play').onclick=()=>timer?pause():play();$('step').onclick=()=>{pause();advance();};$('finish').onclick=()=>{pause();position=result.trace.length-1;render();};$('progress').oninput=()=>{pause();position=Number($('progress').value);render();};$('view').onchange=route;$('retry').onclick=init;init();
