const $=id=>document.getElementById(id);let n=8,board=Array(8).fill(-1),result=null,position=0,timer=null,worker,ready=false,busy=false,revision=0;
function stop(){clearTimeout(timer);timer=null;$('play').textContent='Play';}
function controls(){$('solve').disabled=!ready||busy;for(const id of ['play','step','finish'])$(id).disabled=busy||!result||position>=result.trace.length-1;$('progress').disabled=busy||!result;}
function attackingPairs(){const pairs=[];for(let a=0;a<n;a++)for(let b=a+1;b<n;b++)if(board[a]>=0&&board[b]>=0&&(board[a]===board[b]||Math.abs(board[a]-board[b])===b-a))pairs.push([a,b]);return pairs;}
function draw(){const pairs=attackingPairs(),bad=new Set(pairs.flat()),event=result?.trace[position];for(const cell of $('board').children){const r=+cell.dataset.row,c=+cell.dataset.col,queen=board[r]===c;let classes=(r+c)%2?'dark':'';if(queen&&bad.has(r))classes+=' attacked';if(event?.row===r&&event?.col===c)classes+=' '+(event.action==='reject'?'reject':event.action==='remove'?'remove':'preview');cell.className=classes;cell.textContent=queen?'♛':event?.action==='reject'&&event.row===r&&event.col===c?'×':'';cell.setAttribute('aria-label',`Row ${r+1}, column ${c+1}${queen?', queen':''}${queen&&bad.has(r)?', attacking':''}`);}
 const count=board.filter(c=>c>=0).length;$('placed').textContent=`${count} / ${n}`;$('conflicts').textContent=pairs.length;$('mode').textContent=result?'Solver playback':'Your board';$('tested').textContent=event?event.tested:'—';$('backtracks').textContent=event?event.backtracks:'—';$('position').textContent=result?`${position} / ${result.trace.length-1}`:'—';$('progress').value=position;
 if(!event)$('status').textContent=count===n&&!pairs.length?'Solved. No queens attack each other.':pairs.length?`${pairs.length} attacking pair${pairs.length===1?'':'s'}. Move a red queen.`:'Place a queen in each row.';
 else{const square=`row ${event.row+1}, column ${event.col+1}`;$('status').textContent=event.action==='start'?'Starting from an empty board.':event.action==='solved'?'Solved. Every queen is safe.':event.action==='unsolved'?'No solution exists for this board size.':event.action==='place'?`Placed a queen at ${square}.`:event.action==='reject'?`Rejected ${square}: another queen attacks it.`:`Backtrack: removed the queen at ${square}.`;}
 controls();}
function invalidate(){stop();revision++;busy=false;result=null;position=0;$('progress').value=0;controls();}
function reset(){invalidate();n=Number($('size').value);board=Array(n).fill(-1);$('board').style.gridTemplateColumns=`repeat(${n},1fr)`;$('board').replaceChildren();for(let r=0;r<n;r++)for(let c=0;c<n;c++){const cell=document.createElement('button');cell.type='button';cell.dataset.row=r;cell.dataset.col=c;cell.tabIndex=r===0&&c===0?0:-1;cell.setAttribute('role','gridcell');$('board').append(cell);}draw();}
function place(cell){if(!cell?.dataset.row)return;const r=+cell.dataset.row,c=+cell.dataset.col;invalidate();board[r]=board[r]===c?-1:c;draw();}
$('board').onclick=e=>place(e.target);
$('board').onkeydown=e=>{const cells=[...$('board').children],i=cells.indexOf(e.target);if(i<0)return;const delta={ArrowRight:1,ArrowLeft:-1,ArrowDown:n,ArrowUp:-n}[e.key];if(delta){e.preventDefault();const target=Math.max(0,Math.min(n*n-1,i+delta));cells[i].tabIndex=-1;cells[target].tabIndex=0;cells[target].focus();}};
function show(){board=result.trace[position].board.slice();draw();}
function step(){if(result&&position<result.trace.length-1){position++;show();}}
function play(){step();if(position<result.trace.length-1){$('play').textContent='Pause';timer=setTimeout(play,+$('delay').value);}else stop();}
function fail(){stop();ready=false;busy=false;controls();$('runtime').textContent='Solver couldn’t load. You can still play.';$('retry').hidden=false;}
function init(){if(worker)worker.terminate();ready=false;busy=false;controls();$('retry').hidden=true;$('runtime').textContent='Loading Python solver…';worker=new Worker('worker.js',{type:'module'});worker.onerror=fail;worker.onmessage=({data})=>{if(data.id!==undefined&&data.id!==revision)return;if(data.type==='ready'){ready=true;$('runtime').textContent='Python solver ready.';controls();}else if(data.type==='error')fail();else{result=data.result;busy=false;position=0;$('progress').max=result.trace.length-1;show();}};}
$('solve').onclick=()=>{invalidate();busy=true;board=Array(n).fill(-1);draw();$('status').textContent='Solving from an empty board…';worker.postMessage({id:revision,n});};$('play').onclick=()=>timer?stop():play();$('step').onclick=()=>{stop();step();};$('finish').onclick=()=>{stop();position=result.trace.length-1;show();};$('clear').onclick=reset;$('size').onchange=reset;$('progress').oninput=()=>{stop();position=+$('progress').value;show();};$('retry').onclick=init;reset();init();
